# Generated by Django 6.0.2 on 2026-02-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_remove_post_ig_id_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
