# Generated by Django 6.0.2 on 2026-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_post_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ig_comment_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
