# Generated by Django 6.0.2 on 2026-02-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_remove_comment_ig_comment_id_alter_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='message',
        ),
    ]
